// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqBfsZI9W3ZpEDAB86WajOO2mnqp3Dy2o',
    appId: '1:640108950461:web:4c59a26fb3d70bbda8d8d4',
    messagingSenderId: '640108950461',
    projectId: 'weather-app-91fdc',
    authDomain: 'weather-app-91fdc.firebaseapp.com',
    storageBucket: 'weather-app-91fdc.appspot.com',
    measurementId: 'G-PWG4PD6V7Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPScSemxC3EjkJsa1lNE1R-HMNqrTHZgs',
    appId: '1:640108950461:android:53316e9851e38e7ea8d8d4',
    messagingSenderId: '640108950461',
    projectId: 'weather-app-91fdc',
    storageBucket: 'weather-app-91fdc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYHt5Uwgn4iHujLMvaZeTjehUQslH8oqo',
    appId: '1:640108950461:ios:9baf6548f042e541a8d8d4',
    messagingSenderId: '640108950461',
    projectId: 'weather-app-91fdc',
    storageBucket: 'weather-app-91fdc.appspot.com',
    iosClientId: '640108950461-ej2aokhjaqgk50ihcfq2m958jmio7ihe.apps.googleusercontent.com',
    iosBundleId: 'com.example.weatherApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYHt5Uwgn4iHujLMvaZeTjehUQslH8oqo',
    appId: '1:640108950461:ios:dc0304cf3168fe6ea8d8d4',
    messagingSenderId: '640108950461',
    projectId: 'weather-app-91fdc',
    storageBucket: 'weather-app-91fdc.appspot.com',
    iosClientId: '640108950461-dvt76bj2qrhjvks4sah41nd8d7flgeqr.apps.googleusercontent.com',
    iosBundleId: 'com.example.weatherApp.RunnerTests',
  );
}
